baseURL = "/"
languageCode = "en-us"
title = "Gopi Palaniappan"
theme = "tags07"
#publishdir = "out"

# Enable Disqus
disqusShortname = "yihui"
hasCJKLanguage = true
rssLimit = 100

summarylength = 10
enableEmoji = true
enableRobotsTXT = true


# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

footnotereturnlinkcontents = "↩"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"
  en = "/post/:year/:month/:day/:slug/"



[blackfriday]
    extensionsmask = ["noIntraEmphasis"]
    fractions = false

