  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/en/about/"

  [[main]]
  name = "Blog"
  weight = 500
  identifier = "blog"
  url = "/en/"

  [[main]]
  name = "Subscribe"
  weight = 600
  identifier = "subscribe"
  url = "index.xml"


################

  [[en]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[en]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/en/about/"

  [[en]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "/en/"

  [[en]]
  name = "Todo"
  weight = 400
  identifier = "todo"
  url = "/todo/"

################

  [[knitr]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[knitr]]
  name = "Knitr"
  weight = 200
  identifier = "knitr"
  url = "/knitr/"

  [[knitr]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "/en/"

  [[knitr]]
  name = "Examples"
  weight = 400
  identifier = "demo"
  url = "/knitr/demo/"



################

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"


